{
	"_Type": "Action.Type.ToastMessage",
	"OnSuccess": "/ZSAM2305/Rules/Operations/ZNavOperationCompletePagePostScan.js",
	"Message": "Equipment matched",
	"Duration": 2,
	"IsIconHidden": false,
	"Animated": true,
	"MaxNumberOfLines": 1
}